services:
  app:
    build: .
    volumes:
      - ./data:/app/data
      - .:/app
    environment:
      - FLASK_ENV=production
      - PYTHONPATH=/app
    expose:
      - 8000
    command: bash -c "python -m flask run --host=0.0.0.0 --port=8000"  # 改用 flask run 命令调试

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app